using Ambev.DeveloperEvaluation.Domain.Common;
using Ambev.DeveloperEvaluation.Domain.Exceptions;
using Ambev.DeveloperEvaluation.Domain.ValueObjects;

namespace Ambev.DeveloperEvaluation.Domain.Entities;

// Customer, branch and products are external identities (id + denormalized name) owned by other bounded contexts.
public class Sale : AuditableEntity
{
    private readonly List<SaleItem> _items = [];

    // Generated by the database on insert.
    public long SaleNumber { get; private set; }
    public DateTime SaleDate { get; private set; }
    public CustomerRef Customer { get; private set; } = null!;
    public BranchRef Branch { get; private set; } = null!;

    // Cancelled items do not count.
    public decimal TotalAmount { get; private set; }

    // Derived from the non-cancelled items, not persisted.
    public decimal GrossAmount => ActiveItems.Sum(i => i.GrossAmount);
    public decimal DiscountAmount => ActiveItems.Sum(i => i.DiscountAmount);

    public bool IsCancelled { get; private set; }
    public DateTime? CancelledAt { get; private set; }

    public IReadOnlyCollection<SaleItem> Items => _items.AsReadOnly();

    private IEnumerable<SaleItem> ActiveItems => _items.Where(i => !i.IsCancelled);

    private Sale() { }

    // Sale

    public static Sale Create(DateTime saleDate, CustomerRef customer, BranchRef branch)
    {
        var sale = new Sale { Id = Guid.NewGuid() };
        sale.SetDetails(saleDate, customer, branch);
        return sale;
    }

    public void UpdateDetails(DateTime saleDate, CustomerRef customer, BranchRef branch)
    {
        EnsureNotCancelled();
        SetDetails(saleDate, customer, branch);
    }

    public void Cancel()
    {
        EnsureNotCancelled();
        IsCancelled = true;
        CancelledAt = DateTime.UtcNow;
    }

    // Items

    // An active line for the same product is consolidated, so the discount tier is recalculated on the total quantity.
    public SaleItem AddItem(ProductRef product, int quantity, decimal unitPrice)
    {
        EnsureNotCancelled();

        if (product is null) throw new DomainException("Product must be provided.");
        if (quantity <= 0) throw new DomainException("Quantity must be greater than zero.");

        var item = FindActiveItemByProduct(product.Id);
        if (item is null)
        {
            item = new SaleItem(Id, product, quantity, unitPrice);
            _items.Add(item);
        }
        else
        {
            if (item.UnitPrice != unitPrice)
                throw new DomainException($"Product {product.Id} was informed with different unit prices.");

            item.ChangeQuantity(item.Quantity + quantity);
        }

        RecalculateTotal();
        return item;
    }

    // Relative change: clients act without knowing the current quantity, so concurrent adjustments
    // add up instead of overwriting each other.
    public SaleItem AdjustItemQuantity(Guid itemId, int delta)
    {
        EnsureNotCancelled();

        if (delta == 0)
            throw new DomainException("Quantity delta must be different from zero.");

        var item = GetItem(itemId);
        var quantity = item.Quantity + delta;
        if (quantity <= 0)
            throw new DomainException("Resulting quantity must be greater than zero. Cancel the item to remove it.");

        item.ChangeQuantity(quantity);
        RecalculateTotal();
        return item;
    }

    // Cancels the whole line. It is kept for history but no longer counts in the total.
    public void CancelItem(Guid itemId)
    {
        EnsureNotCancelled();
        GetItem(itemId).Cancel(DateTime.UtcNow);
        RecalculateTotal();
    }

    // Helpers

    private void SetDetails(DateTime saleDate, CustomerRef customer, BranchRef branch)
    {
        if (saleDate == default)
            throw new DomainException("Sale date must be provided.");

        SaleDate = saleDate.Kind switch
        {
            DateTimeKind.Utc => saleDate,
            DateTimeKind.Local => saleDate.ToUniversalTime(),
            _ => DateTime.SpecifyKind(saleDate, DateTimeKind.Utc)
        };
        Customer = customer ?? throw new DomainException("Customer must be provided.");
        Branch = branch ?? throw new DomainException("Branch must be provided.");
    }

    private void EnsureNotCancelled()
    {
        if (IsCancelled)
            throw new DomainException("A cancelled sale cannot be modified.");
    }

    private SaleItem? FindActiveItemByProduct(Guid productId) =>
        _items.FirstOrDefault(i => !i.IsCancelled && i.Product.Id == productId);

    private SaleItem GetItem(Guid itemId) =>
        _items.FirstOrDefault(i => i.Id == itemId)
        ?? throw new DomainException($"Sale item {itemId} not found in sale {Id}.");

    private void RecalculateTotal() =>
        TotalAmount = ActiveItems.Sum(i => i.TotalAmount);
}
