<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Rebus" Version="8.9.5" />
    <PackageReference Include="Rebus.RabbitMq" Version="10.1.1" />
    <PackageReference Include="Rebus.ServiceProvider" Version="10.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ambev.DeveloperEvaluation.Application\Ambev.DeveloperEvaluation.Application.csproj" />
    <ProjectReference Include="..\Ambev.DeveloperEvaluation.ORM\Ambev.DeveloperEvaluation.ORM.csproj" />
  </ItemGroup>

</Project>
