using Ambev.DeveloperEvaluation.Application.Sales.Events;
using Ambev.DeveloperEvaluation.Domain.Entities;
using Ambev.DeveloperEvaluation.Unit.Domain.Entities.TestData;
using FluentAssertions;
using Xunit;

namespace Ambev.DeveloperEvaluation.Unit.Application;

public class SaleIntegrationEventsTests
{
    private const long SaleNumber = 42;

    [Fact(DisplayName = "SaleCreated should carry the full sale state")]
    public void Given_Sale_When_Created_Then_ShouldSnapshotSale()
    {
        var sale = SaleTestData.GenerateValidSale();
        var kept = sale.AddItem(SaleTestData.GenerateProduct(), 10, 12.50m);
        var cancelled = sale.AddItem(SaleTestData.GenerateProduct(), 2, 10m);
        sale.CancelItem(cancelled.Id);
        SetSaleNumber(sale);

        var message = SaleIntegrationEvents.Created(sale);

        message.EventId.Should().NotBeEmpty();
        message.SaleId.Should().Be(sale.Id);
        message.SaleNumber.Should().Be(SaleNumber);
        message.SaleDate.Should().Be(sale.SaleDate);
        message.CustomerId.Should().Be(sale.Customer.Id);
        message.CustomerName.Should().Be(sale.Customer.Name);
        message.BranchId.Should().Be(sale.Branch.Id);
        message.BranchName.Should().Be(sale.Branch.Name);
        message.TotalAmount.Should().Be(100m);
        message.Items.Should().HaveCount(2);

        var keptLine = message.Items.Single(i => i.ItemId == kept.Id);
        keptLine.ProductId.Should().Be(kept.Product.Id);
        keptLine.ProductName.Should().Be(kept.Product.Name);
        keptLine.Quantity.Should().Be(10);
        keptLine.UnitPrice.Should().Be(12.50m);
        keptLine.DiscountRate.Should().Be(0.20m);
        keptLine.DiscountAmount.Should().Be(25m);
        keptLine.TotalAmount.Should().Be(100m);
        keptLine.IsCancelled.Should().BeFalse();

        message.Items.Single(i => i.ItemId == cancelled.Id).IsCancelled.Should().BeTrue();
    }

    [Fact(DisplayName = "SaleModified should carry the full sale state")]
    public void Given_Sale_When_Modified_Then_ShouldSnapshotSale()
    {
        var sale = SaleTestData.GenerateValidSale();
        sale.AddItem(SaleTestData.GenerateProduct(), 3, 10m);
        SetSaleNumber(sale);

        var message = SaleIntegrationEvents.Modified(sale);

        message.SaleNumber.Should().Be(SaleNumber);
        message.TotalAmount.Should().Be(30m);
        message.Items.Should().ContainSingle();
    }

    [Fact(DisplayName = "SaleCancelled should carry the cancellation date and total")]
    public void Given_CancelledSale_When_Mapped_Then_ShouldCarryCancellation()
    {
        var sale = SaleTestData.GenerateValidSale();
        sale.AddItem(SaleTestData.GenerateProduct(), 3, 10m);
        sale.Cancel();
        SetSaleNumber(sale);

        var message = SaleIntegrationEvents.Cancelled(sale);

        message.SaleId.Should().Be(sale.Id);
        message.SaleNumber.Should().Be(SaleNumber);
        message.CancelledAt.Should().Be(sale.CancelledAt!.Value);
        message.TotalAmount.Should().Be(30m);
    }

    [Fact(DisplayName = "ItemCancelled should carry the item and the new sale total")]
    public void Given_CancelledItem_When_Mapped_Then_ShouldCarryItemAndTotal()
    {
        var sale = SaleTestData.GenerateValidSale();
        sale.AddItem(SaleTestData.GenerateProduct(), 2, 10m);
        var item = sale.AddItem(SaleTestData.GenerateProduct(), 5, 10m);
        sale.CancelItem(item.Id);
        SetSaleNumber(sale);

        var message = SaleIntegrationEvents.ItemCancelled(sale, item);

        message.SaleId.Should().Be(sale.Id);
        message.SaleNumber.Should().Be(SaleNumber);
        message.ItemId.Should().Be(item.Id);
        message.ProductId.Should().Be(item.Product.Id);
        message.ProductName.Should().Be(item.Product.Name);
        message.Quantity.Should().Be(5);
        message.CancelledAt.Should().Be(item.CancelledAt!.Value);
        message.SaleTotalAmount.Should().Be(20m);
    }

    [Fact(DisplayName = "Each message should get its own event id")]
    public void Given_SameSale_When_MappedTwice_Then_ShouldGenerateDistinctIds()
    {
        var sale = SaleTestData.GenerateValidSale();

        SaleIntegrationEvents.Modified(sale).EventId.Should().NotBe(SaleIntegrationEvents.Modified(sale).EventId);
    }

    // The sale number is generated by the database on insert.
    private static void SetSaleNumber(Sale sale) =>
        typeof(Sale).GetProperty(nameof(Sale.SaleNumber))!.SetValue(sale, SaleNumber);
}
